### PR TITLE
Added a dark theme 'beamerthemetudo_dark.sty' and a progress bar.

### PR DESCRIPTION
**Pull request by aknierim**
Added a dark theme 'beamerthemetudo_dark.sty' and a progress bar. 
Added a dark theme for plots (plots/darkmode.mplstyle) that applies
automatically when compiling with make.
Added matplotlibrc with optional settings.

Use
$ make <all | light | dark>
to compile both or either the light or the dark theme.

### CODE REVIEW

**Review by maxnoe — CHANGES_REQUESTED** [review]
I'd be happy to include a dark theme, but this pull request is mixing to many things and making completely unrelated changes.

Please:
* Revert any changes not related to the dark theme
* Create the dark theme as an option `dark`, not as a separate beamer theme.

**Comment by aknierim** [comment]
Sure, no problem! Will get to work, once I find some time for it. Probably within the next two weeks.

**Comment by aknierim** [comment]
The dark theme can now be activated via a `dark` option.

**Comment by maxnoe** [comment]
I had a quick look at the example and urls are too dark, can you fix that?

**Comment by maxnoe** [comment]
Something like this:

```
% selection of the main colors for the light/dark themes
\if@dark%
  \colorlet{maincolor}{darkmode}% background color
  \colorlet{fgcolor}{white}% foreground color, e.g. for text
  \hypersetup{colorlinks=true, linkcolor=lightgray, urlcolor=tulight}
\else%
  \colorlet{maincolor}{white}%
  \colorlet{fgcolor}{darkgray}%
  \hypersetup{colorlinks=true, linkcolor=darkgray, urlcolor=tudark}
\fi

```

**Comment by aknierim** [comment]
`tulight` looks too much like the rest of the text imo, making it harder to recognize it as an URL. I tried something like `tugreen!80!white`, but I shall let you be the judge of that :)

**Review by maxnoe — APPROVED** [review]

**Pull request merged**
